# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/serve_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/serve_data.proto\x12\ndataserver\"+\n\rwrite_request\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x1b\n\x0cread_request\x12\x0b\n\x03key\x18\x01 \x02(\t\"\x1e\n\rresponse_read\x12\r\n\x05value\x18\x01 \x02(\t\"\x1a\n\x08response\x12\x0e\n\x06status\x18\x01 \x02(\t2\xc9\x01\n\x0b\x64\x61ta_server\x12;\n\x04read\x12\x18.dataserver.read_request\x1a\x19.dataserver.response_read\x12=\n\nwrite_data\x12\x19.dataserver.write_request\x1a\x14.dataserver.response\x12>\n\x0bupdate_data\x12\x19.dataserver.write_request\x1a\x14.dataserver.response')



_WRITE_REQUEST = DESCRIPTOR.message_types_by_name['write_request']
_READ_REQUEST = DESCRIPTOR.message_types_by_name['read_request']
_RESPONSE_READ = DESCRIPTOR.message_types_by_name['response_read']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
write_request = _reflection.GeneratedProtocolMessageType('write_request', (_message.Message,), {
  'DESCRIPTOR' : _WRITE_REQUEST,
  '__module__' : 'protos.serve_data_pb2'
  # @@protoc_insertion_point(class_scope:dataserver.write_request)
  })
_sym_db.RegisterMessage(write_request)

read_request = _reflection.GeneratedProtocolMessageType('read_request', (_message.Message,), {
  'DESCRIPTOR' : _READ_REQUEST,
  '__module__' : 'protos.serve_data_pb2'
  # @@protoc_insertion_point(class_scope:dataserver.read_request)
  })
_sym_db.RegisterMessage(read_request)

response_read = _reflection.GeneratedProtocolMessageType('response_read', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_READ,
  '__module__' : 'protos.serve_data_pb2'
  # @@protoc_insertion_point(class_scope:dataserver.response_read)
  })
_sym_db.RegisterMessage(response_read)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'protos.serve_data_pb2'
  # @@protoc_insertion_point(class_scope:dataserver.response)
  })
_sym_db.RegisterMessage(response)

_DATA_SERVER = DESCRIPTOR.services_by_name['data_server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRITE_REQUEST._serialized_start=39
  _WRITE_REQUEST._serialized_end=82
  _READ_REQUEST._serialized_start=84
  _READ_REQUEST._serialized_end=111
  _RESPONSE_READ._serialized_start=113
  _RESPONSE_READ._serialized_end=143
  _RESPONSE._serialized_start=145
  _RESPONSE._serialized_end=171
  _DATA_SERVER._serialized_start=174
  _DATA_SERVER._serialized_end=375
# @@protoc_insertion_point(module_scope)
